language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: false
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10"
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
